"""Initial migration

Revision ID: ad89e754f9fe
Revises: 
Create Date: 2024-10-06 02:31:32.645854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad89e754f9fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('image', 'document', 'video'), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('message_type', sa.Enum('text', 'image', 'file', 'markdown'), nullable=False),
    sa.Column('status', sa.Enum('sent', 'delivered', 'read'), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('files')
    op.drop_table('users')
    op.drop_table('rooms')
    op.drop_table('communities')
    # ### end Alembic commands ###
